name: Notify Slack

on:
  workflow_call:

outputs:
  slack_ts:
    description: "Slack message timestamp for thread replies"
    value: ${{ steps.slack.outputs.slack_ts }}

jobs:
  notify:
    runs-on: ubuntu-latest
    outputs:
      slack_ts: ${{ steps.slack.outputs.slack_ts }}

    steps:
      - name: Notify Slack with summary
        id: slack
        env:
          SLACK_BOT_TOKEN_CI: ${{ secrets.SLACK_BOT_TOKEN_CI }}
        run: |
          SUMMARY=$(cat build-summary.json)

          BUILT=$(echo "$SUMMARY" | jq -r '.built[]?' | sed 's/^/- /' | paste -sd '\n' -)
          FAILED=$(echo "$SUMMARY" | jq -r '
            if (.failed | length) > 0 then
              .failed[] | "- " + (.name // "unknown") + ": " + (.reason // "no reason") + "\n" + (.detail // "")
            else
              empty
            end
          ' | paste -sd '\n\n' -)

          [ -z "$BUILT" ] && BUILT="(none)"
          [ -z "$FAILED" ] && FAILED="(none)"

          FAIL_COUNT=$(echo "$SUMMARY" | jq '.failed | length')

          if [ "$FAIL_COUNT" -gt 0 ]; then
            TEXT="❌ CI build failed on branch *${{ github.ref_name }}*"
          else
            TEXT="✅ CI build succeeded on branch *${{ github.ref_name }}*"
          fi

          MESSAGE=$(echo -e "$TEXT\n\n*Projects built:*\n$BUILT\n\n*Failures:*\n$FAILED")

          CHANNEL_ID="C08TGT4TBGT"
          SLACK_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN_CI" \
            -H "Content-type: application/json" \
            --data "$(jq -n --arg channel "$CHANNEL_ID" --arg text "$MESSAGE" '{channel: $channel, text: $text}')" \
            https://slack.com/api/chat.postMessage)

          TIMESTAMP=$(echo "$SLACK_RESPONSE" | jq -r '.ts // empty')
          if [ -n "$TIMESTAMP" ]; then
            echo "🕒 Slack message timestamp: $TIMESTAMP"
            echo "slack_ts=$TIMESTAMP" >> "$GITHUB_OUTPUT"
          else
            echo "⚠️ Failed to extract timestamp from response: $SLACK_RESPONSE"
          fi
