name: Build

on:
  workflow_call:

outputs:
  artifact_name:
    description: "Name of the artifact uploaded"
    value: ${{ steps.upload.outputs.artifact_name }}

jobs:
  build:
    runs-on: self-hosted

    outputs:
      artifact_name: ${{ steps.upload.outputs.artifact_name }}

    steps:
      - name: Checkout pt-zh-web repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Identify and build changed projects
        run: |
          pnpm ls --depth -1 --json --filter "[${{ github.event.before }}...${{ github.sha }}]" > packages.json
          node scripts/ci/build-changed-projects.js

      - name: Upload built dist folders as artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts-${{ github.sha }}
          path: ./artifacts/**

      - name: Set artifact output
        id: set-output
        run: echo "artifact_name=dist-artifacts-${{ github.sha }}" >> $GITHUB_OUTPUT
